import { NavigationMenu } from "@/components/NavigationMenu";
import "../app/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { isWide, useWindowSize } from "../../util/WindowSize";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lucas Mayall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const { width, height } = useWindowSize();
  const constantMenu = isWide(width);

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta property="og:title" content={metadata.title} key="title" />
      </Head>

      <NavigationMenu />
      <div className={` bg-secondary text-primary py-3 min-h-screen flex flex-col
      ${constantMenu ? "ml-64 px-4 text-lg" : "ml-0 px-2 text-md"}
      
      `}>
        {children}
      </div>
    </>
  );
}
