import { NavigationMenu } from "@/components/NavigationMenu";
import "../app/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lucas Mayall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta property="og:title" content={metadata.title} key="title" />
      </Head>

      <NavigationMenu />
      <div className=" bg-secondary text-primary py-3  pt-16 min-h-screen flex flex-col px-2 md:px-4 text-md md:text-lg">

        {children}
      </div>
    </>
  );
}
