import { NavigationMenu } from "@/components/NavigationMenu";
import "../app/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lucas Mayall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta property="og:title" content={metadata.title} key="title" />
      </Head>

      <NavigationMenu />
      <div className="bg-primary min-h-screen pt-10">
        <div className=" bg-secondary text-primary py-3 px-6 flex-grow">
          {children}
        </div>
      </div>
    </>
  );
}
